### ISSUE TITLE
Suggestion: separate settings "Prefer Block LaTeX" for codeblocks and inline code

### ISSUE THREAD

**Issue by ThiagoRangel7** [Canna71/obsidian-mathpad#3]
We could have 2 separate options in Mathpad's settings:

- Codeblock: Prefer Block LaTeX (ON/OFF)
- Inline: Prefer Block LaTeX (ON/OFF)

I, for example, want to use block LaTeX only when I'm typing in a codeblock, therefore I'd use the first option ON.
When I'm typing inline code, I would like to render inline LaTeX by default, therefore I'd use the second option OFF

**Comment by Canna71** [comment]
Makes sense. As a first release I kept things simple, but I will work on this, thank you for your feedback.

**Comment by Canna71** [comment]
Done in 0.8.7
