### ISSUE TITLE
Suggestion: Slider for Variables

### ISSUE THREAD

**Issue by PhoenixofForce** [Canna71/obsidian-mathpad#5]
I would love to have some sort of slider for variables, so that the value can be manipulated in read mode.

I have something like `a:=slider(from, to, [stepsize], [default value])` in mind.
So as an example you could do:

`a:=slider(1, 10)`
`plot(x^a)=?`

To have a plot that changes when the slider is used.

**Comment by Canna71** [comment]
Thank you, I had it on my roadmap too! ;-)
Hang on...

**Comment by Canna71** [comment]
I have an experimental implementation in pre-release 0.8.8. (you could use BRAT to test it)
Syntax is what you proposed. You could either write:
`a:=slider(1,10)` 
or
`a:=slider(5,1,10)`
if you want to specify a starting value different than the minimum (in the example 5 is the initial value).

**Comment by PhoenixofForce** [comment]
![image](https://user-images.githubusercontent.com/20171324/207872341-18c43b42-1267-426c-9afd-617bf6f0eaf3.png)

I tried to test it. Seems like the logic works(as b+2 equals 5). But there are no visuals (if there should be any). I tried inline and block

**Comment by Canna71** [comment]
Sorry, I forgot to mention this will only work in the sidebar at the moment. Do you feel having sliders in the notes is important to you?

**Comment by PhoenixofForce** [comment]
Oh ok, it indeed works in the sidebar. From my experience, I use notes more than the sidebar. But the longer I think about the more unsure i get, how often I'll use sliders in notes... So i guess having sliders in the notes is more like a nice to have.

**Comment by SekoiaTree** [comment]
Heya! The sliders are pretty cool, but it seems that they don't update plots (fair enough, that sounds hard to do). Additionally, it seems that they can't be slid smoothly? They get stuck browsing a ton of fractions
![image](https://user-images.githubusercontent.com/51149447/210590954-bb4ba814-18b5-4a43-9ca5-8d35b1058bc2.png)

Also adding my vote for sliders in notes; this would allow me to have really nice visualizations to play around with when rereading!

**Comment by Canna71** [comment]
I'll consider adding slider in notes, too.
They should also update plots, though.

Try with `a:=slider(1, 10)` and `plot(sin(a*x))`

You're right they don't "scroll", I will have a look, thank you for reporting this.

**Comment by Canna71** [comment]
Slider should scroll correctly now in 0.8.14

**Comment by SekoiaTree** [comment]
Awesome, thanks!

**Comment by dairaine** [comment]
Hi, thanks for your work. Any chance to have Sliders integrated into the notes  in Obsidian ?
