### ISSUE TITLE
Suggestion: Setting for adjusting decimal precision

### ISSUE THREAD

**Issue by ioan-assenov** [Canna71/obsidian-mathpad#6]
My suggestion is to add a setting which allows you to change the amount of decimal places that are given in a numerical answer. This could be taken a few steps further and include a scientific mode to force display all results in scientific notation regardless of their order of magnitude.

This is an incredibly useful plugin and I am very grateful that you have created it!

**Comment by Canna71** [comment]
Thank you for your feedback. I already had this on my roadmap (it is a bit trickier than one may think).
 I'll work on this.

**Comment by Canna71** [comment]
Done in 0.8.7
