### ISSUE TITLE
Suggestions for Plot engine

### ISSUE THREAD

**Issue by ThiagoRangel7** [Canna71/obsidian-mathpad#7]
It's currently impossible to plot a function that has more than one value for $Y$ for each value of $X$ (for example, the circle function $y^2+x^2=25$ (or, in another form, $y = \pm \sqrt {25 - x^2}$

It would also be good if we could plot points.

Maybe Mathpad could plot it like [Desmos](https://www.desmos.com/calculator) does it. Something like `` `plot(y^2 + x^2 = 25)` `` and `` `plot( (3,2) )` ``.
![image](https://user-images.githubusercontent.com/39643122/207363715-4ee148b0-3aa5-4bbd-9706-58e024883a0f.png)

 Like

**Comment by Canna71** [comment]
It should be possible, function-plot supports it. I'll have a look.

**Comment by Canna71** [comment]
I added experimental support in 0.8.13 you could install with BRAT
No doc yet, but here is an example plot:

`plot(x^2+y^2=25, x^2,[[1,2],[3,4]],[-10,10])`

Note: points are vectors of vectors
