### ISSUE TITLE
Bug(?): Inline results do not work if the text is formatted

### ISSUE THREAD

**Issue by Mixpap** [Canna71/obsidian-mathpad#8]
Hey, 
as the title suggests, it seems that inline results cannot work if the text is formatted, i.e. in bullets/lists, headings, bold etc.

**Comment by Canna71** [comment]
It's true; I'll have a look.

**Comment by Canna71** [comment]
Hi, I have a tentative fix in pre-release 0.8.8
If you'd like you could install it using BRAT and provide feedback

Thank you

**Comment by Mixpap** [comment]
I tried the 0.8.8 version, indeed inline results are now working in lists. However still doesn't work in headings. 
Very nice work by the way, thanks for this. I only miss the the scientific notation.

**Comment by Canna71** [comment]
Thank you, I'll keep testing it because I am afraid some edge cases could still be missed. Unfortunately the implementation is more complicated than one can image because in order to keep performance acceptable with several inline-code sections, I had to implement a bunch of optimisations in order to avoid recalculating at every keypress.

Indeed it is not working on headings. I will work on that.

**Comment by Canna71** [comment]
I did further fixes in 0.8.9

**Comment by Canna71** [comment]
In version 0.8.11 there is further support for Scientific Notation.

**Comment by Mixpap** [comment]
Looking at version 0.8.11, it working as a charm. Thank you.
Your plugin (along with scientific notation) supercharged my usage in obsidian at 100%. 
If you (or we as part of the community) also can add units it will be an overkill.

There is very nice plugin for units called numerals (https://github.com/gtg922r/obsidian-numerals) which I think uses mathjs. I don't know if someone can combine these two libraries.

**Comment by Canna71** [comment]
I know _mathjs_. It's great for calculations, but not so much for symbolic math and algebra in general.
I also considered using _algebrite_ which has units, but run shorter on other things. So in the end I chose _nerdamer_, which has almost everything, except units.

I will close this issue for the time being.
